export component ScrollView {
    in property <bool> enabled: true;
    out property <length> visible_width <=> flickable.width;
    out property <length> visible_height <=> flickable.height;
    in_out property <length> viewport_width <=> flickable.viewport_width;
    in_out property <length> viewport_height <=> flickable.viewport_height;
    in_out property <length> viewport_x <=> flickable.viewport_x;
    in_out property <length> viewport_y <=> flickable.viewport_y;
    in_out property <bool> has_focus;

    callback scrolled <=> flickable.flicked;

    property <length> scroll_bar_size: 8px;
    property <length> scroll_bar_padding: 1px;

    min_height: 50px;
    min_width: 50px;
    horizontal_stretch: 1;
    vertical_stretch: 1;
    preferred_height: 100%;
    preferred_width: 100%;

    flickable := Flickable {
        x: 0;
        y: 0;
        width: root.width;
        height: root.height;

        @children
    }
}

//import {ListView} from "ui-libraries/material/src/material.slint";
export component Test123 inherits ScrollView {}

export component ListView inherits Test123 {}

// export component DHV inherits Rectangle {
//     preferred-width: 600px;
//     preferred-height: 600px;

//     ListView {
//         property<length> entry_height: 600px;
//         viewport-width: parent.width;

//         for my-color[index] in [ #e11, #1a2, #23d ]: Rectangle {
//             height: 100px;
//             width: parent.width;
//             background: my-color;
//         }

//         scrolled => {
//             debug("Scrolled");
//         }
//     }
// }

component Item inherits Rectangle {
    height: 60px;
    background: @linear-gradient(0, greenyellow, skyblue);
}

export component DHV inherits Rectangle {
    preferred-width: 600px;
    preferred-height: 600px;

    ListView {
        property<length> entry_height: 600px;
        viewport-width: parent.width;

        // VerticalLayout {
            for i in 100: Item { }
            // for my-color[index] in [ #e11, #1a2, #23d ]: Rectangle {
            //     height: 100px;
            //     background: my-color;
            // }
        // }

        scrolled => {
            debug("Scrolled");
        }
    }
}