// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { ListView  } from "std-widgets.slint";

export component TestCase inherits Window {
    width: 400px;
    height: 540px;

    in-out property <length> content-y <=> -lv.content-y;
    out property listview-content-height <=> listview.content-height;
    out property listview-content-width <=> listview.content-width;
    out property listview-preferred-height <=> listview.preferred-height;

    out property <bool> test: true;

    callback ensure_visible_row(int, ScrollMode);
    ensure_visible_row(row, mode) => {
        listview.ensure_row_visible(row, mode)
    }

    listview := ListView {
        for data in [
            { text: "Blue", color: #0000ff, bg: #eeeeee},
            { text: "Red", color: #ff0000, bg: #eeeeee},
            { text: "Green", color: #00ff00, bg: #eeeeee},
            { text: "Yellow", color: #ffff00, bg: #222222 },
            { text: "Black", color: #000000, bg: #eeeeee },
            { text: "White", color: #ffffff, bg: #222222 },
            { text: "Magenta", color: #ff00ff, bg: #eeeeee },
            { text: "Cyan", color: #00ffff, bg: #222222 },
        ] : delegate := Rectangle {
            height: 200px;
            background: @linear-gradient(90deg, data.bg,data.bg.brighter(0.5));
        }
    }
}

/*
```rust
const SCROLL_MODE: ScrollMode = ScrollMode::Instant;
const BLUE_RECTANGLE_INDEX: i32 = 0;
const RED_RECTANGLE_INDEX: i32 = 1;
const BLACK_RECTANGLE_INDEX: i32 = 4;
const CYAN_RECTANGLE_INDEX: i32 = 7;
const RECTANGLE_HEIGHT: f32 = 200.;

let instance = TestCase::new().unwrap();
assert!(instance.get_test());
assert_eq!(instance.get_listview_content_height(), 8. * RECTANGLE_HEIGHT);

instance.ensure_visible_row(BLUE_RECTANGLE_INDEX, SCROLL_MODE);





```

*/
